In [1]:
import numpy as np

In [13]:
a = np.array([10,20,5,4,15])
a[4]
ones = np.ones((5,4))
print(ones)
type(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


numpy.ndarray

In [14]:
cabeceras = [('nombre','S10'),('edad', int)]
datos = [('pepe', 10),('jUAN', 12),('Javier',42),('samuel',12),('Andres', 15),('jey',13),('Jaime',25)]
usuarios = np.array(datos,dtype= cabeceras)
usuarios

array([(b'pepe', 10), (b'jUAN', 12), (b'Javier', 42), (b'samuel', 12),
       (b'Andres', 15), (b'jey', 13), (b'Jaime', 25)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

In [15]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
np.arange(5,50,10)

array([ 5, 15, 25, 35, 45])

In [21]:
#Matriz con elementos de un solo valor.
np.full((3,5), 12)

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])

In [22]:
#Generar matriz diagonal en numpy
np.diag([1,1,1,2])


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 2]])

In [24]:
#Reto Crear arraglo en numpy y organizarlo por pais.

cabecera = [('pais', 'S10'),('Poblacion en M', int)]
datos = [('Brazil', 212559417),('Colombia', 51609474),('Argentina','47327407'),('Peru','33050325')]
paisesLatam = np.array(datos, dtype = cabecera) 
paisesLatam

array([(b'Brazil', 212559417), (b'Colombia',  51609474),
       (b'Argentina',  47327407), (b'Peru',  33050325)],
      dtype=[('pais', 'S10'), ('Poblacion en M', '<i8')])

In [27]:
np.sort(paisesLatam, order ='pais')

array([(b'Argentina',  47327407), (b'Brazil', 212559417),
       (b'Colombia',  51609474), (b'Peru',  33050325)],
      dtype=[('pais', 'S10'), ('Poblacion en M', '<i8')])